Project.WEBUI/Controllers/ShoppingController.cs
using Project.BLL.DesignPatterns.GenericRepository.ConcRep;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList; //bizim sayfalama işlemlerini yapmak icin indirdigimiz kütüphaneyi kullandıgımız alan.. Bu klasik PagedList kütüphanesi BackEnd'de her türlü destegi sunarken RazorView'in kullanılabildigi alan sadece MVC'dir...O yüzden
using Project.WEBUI.Models;
using Project.WEBUI.Models.ShoppingTools;
using Project.ENTITIES.Models;
using Project.WEBUI.AuthenticationClasses;
using System.Net.Http;
using System.Threading.Tasks;
using Project.COMMON.Tools;

namespace Project.WEBUI.Controllers
{
    public class ShoppingController : Controller
    {

        OrderRepository oRep;
        ProductRepository pRep;
        CategoryRepository cRep;
        OrderDetailRepository odRep;

        public ShoppingController()
        {
            oRep = new OrderRepository();
            pRep = new ProductRepository();
            cRep = new CategoryRepository();
            odRep = new OrderDetailRepository();
        }

        // GET: Shopping

        //Sayfalama işlemleri yapmak icin Pagination kütüphanesinden yararlanıyoruz (PagedList)
        public ActionResult ShoppingList(int? page,int? categoryID) //nullable int vermemizin sebebi aslında buradaki int'in sayfa sayımızı temsil edecek olmasıdır...Ancak birisi direkt alısveriş sayfasına ulastıgında sayfa sayısını gönderemeyeceginden bu sekilde de Action'ın calısabilmesini istiyoruz.
        {


            //string a = "Cagri";

            //string b = a??"Cagri"; //eger a null ise b'ye null at...null degilse b'ye git a'nın degerini at demektir...

            //            page??1

            //Alt tarafta page?? demek page null geliyorsa demektir

            PAVM pavm = new PAVM
            {
                PagedProducts = categoryID == null? pRep.GetActives().ToPagedList(page??1,9):pRep.Where(x=>x.CategoryID==categoryID).ToPagedList(page??1,9),//eger page parametresi null ise(??) sayfamız 1 olacak ve her sayfada 9 veri listelenecek...
                Categories = cRep.GetActives()
            };

            if (categoryID != null) TempData["catID"] = categoryID;

            return View(pavm);
        }

        public ActionResult AddToCart(int id)
        {
            Cart c = Session["scart"] == null ? new Cart() : Session["scart"] as Cart;

            Product eklenecekUrun = pRep.Find(id);

            CartItem ci = new CartItem
            {
                ID = eklenecekUrun.ID,
                Name = eklenecekUrun.ProductName,
                Price = eklenecekUrun.UnitPrice,
                ImagePath = eklenecekUrun.ImagePath
            };

            c.SepeteEkle(ci);
            Session["scart"] = c;
            return RedirectToAction("ShoppingList");


        }

        public ActionResult CartPage()
        {
            if (Session["scart"]!=null)
            {
                CartPageVM cpvm = new CartPageVM();
                Cart c = Session["scart"] as Cart;
                cpvm.Cart = c;
                return View(cpvm);

            }

            TempData["sepetBos"] = "Sepetinizde ürün bulunmamaktadır";
            return RedirectToAction("ShoppingList");
        }

        public ActionResult DeleteFromCart(int id)
        {
            if (Session["scart"]!=null)
            {
                Cart c = Session["scart"] as Cart;
                c.SepettenSil(id);

                if (c.Sepetim.Count==0)
                {
                    Session.Remove("scart");
                    TempData["sepetBos"] = "Sepetinizde ürün bulunmamaktadır";
                    return RedirectToAction("ShoppingList");
                }
                return RedirectToAction("CartPage");
            }
            return RedirectToAction("ShoppingList");
        }

        //[MemberAuthentication]
        public ActionResult SiparisiOnayla()
        {
            AppUser mevcutKullanici;
            if (Session["member"]!=null)
            {
                mevcutKullanici = Session["member"] as AppUser;
            }
            else
            {
                TempData["anonim"] = "Kullanıcı uye degil";
            }
            return View();

        }




        //https://localhost:44363/api/Payment/ReceivePayment

        [HttpPost]
        public ActionResult SiparisiOnayla(OrderVM ovm)
        {
            bool result;
            Cart sepet = Session["scart"] as Cart;

            ovm.Order.TotalPrice = ovm.PaymentVM.ShoppingPrice = sepet.TotalPrice.Value;

            //API kullanımı 
            //WebApiRestService.WebAPIClient kütüphanesi indirmeyi unutmayın..Yoksa BackEnd'den API'ya istek gönderemezsiniz...
            using (HttpClient client=new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44363/api/");

                Task<HttpResponseMessage> postTask = client.PostAsJsonAsync("Payment/ReceivePayment", ovm.PaymentVM);

                HttpResponseMessage sonuc;

                try
                {
                    sonuc = postTask.Result;
                }
                catch (Exception ex)
                {

                    TempData["baglantiRed"] = "Banka baglantıyı reddetti";
                    return RedirectToAction("ShoppingList");
                }

                if (sonuc.IsSuccessStatusCode)
                {
                    result = true;
                }
                else result = false;

                if (result)
                {
                    if (Session["member"] !=null)
                    {
                        AppUser kullanici = Session["member"] as AppUser;
                        ovm.Order.AppUserID = kullanici.ID;
                        ovm.Order.UserName = kullanici.UserName;
                    }
                    else
                    {
                        ovm.Order.AppUserID = null;
                        ovm.Order.UserName = TempData["anonim"].ToString();
                    }

                    oRep.Add(ovm.Order); //OrderRepository bu noktada Order'i eklerken onun ID'sini olusturuyor...

                    foreach (CartItem item in sepet.Sepetim)
                    {
                        OrderDetail od = new OrderDetail();
                        od.OrderID = ovm.Order.ID;
                        od.ProductID = item.ID;
                        od.TotalPrice = item.SubTotal;
                        od.Quantity = item.Amount;
                        odRep.Add(od);

                        //Stoktan düsmesini istiyorsanız 
                        Product stokDus = pRep.Find(item.ID);
                        stokDus.UnitsInStock -= item.Amount;
                        pRep.Update(stokDus);
                    }

                    TempData["odeme"] = "Siparişiniz bize ulasmıstır...Tesekkür ederiz";

                    MailSender.Send(ovm.Order.Email, body: $"Siparişiniz basarıyla alındı...{ovm.Order.TotalPrice}");

                    return RedirectToAction("ShoppingList");




                }

                else
                {
                    TempData["sorun"] = "Odeme ile ilgili bir sorun olustu..Lutfen bankanız iletişime geciniz";
                    return RedirectToAction("ShoppingList");
                }



            }

            
           
        }



    }
}

Project.WEBUI/Views/Shopping/CartPage.cshtml
@model CartPageVM
@{
    ViewBag.Title = "CartPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="jumbotron">
    Odemeniz gereken Toplam Tutar => @Model.Cart.TotalPrice ... Siparişi onaylamak icin lütfen @Html.ActionLink("Tıklayınız","SiparisiOnayla")
</div>


<div class="row product-list">
    @foreach (CartItem item in Model.Cart.Sepetim)
    {
        <div class="col-md-4">
            <section class="panel">
                <div class="pro-img-box">
                    @if (item.ImagePath == null)
                    {
                        <img src="~/Pictures/CityLife.jpg" width="100" height="300" alt="Resim Yok" title="@item.Name" />
                    }
                    else
                    {
                        <img src="@item.ImagePath" width="100" height="300" alt="Resim Yok" title="@item.Name" />
                    }

                    <a href="@Url.Action("DeleteFromCart",new { id=item.ID})" class="adtocart">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>



                </div>

                <div class="panel-body text-center">
                    <h4>
                        <a href="#" class="pro-title">
                            @item.Name x @item.Amount



                        </a>
                    </h4>
                    <p class="price">$@item.SubTotal</p>
                </div>


            </section>
        </div>
    }
</div>

Project.WEBUI/Views/Shopping/ShoppingList.cshtml
@model PAVM
@{
    ViewBag.Title = "ShoppingList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<h2 style="color:red">@TempData["sorun"]</h2>
<h2 style="color:red">@TempData["sepetBos"]</h2>
<h2 style="color:red">@TempData["baglantiRed"]</h2>


<div class="row">
    <div class="col-md-3">
        <section class="panel">
            <div class="panel-body">
                <h2 style="color:#313267">Kategoriler</h2> <br />
                <ul>
                    @foreach (Category item in Model.Categories)
                    {
                        <li style="padding-top:3px">@Html.ActionLink(item.CategoryName, "ShoppingList", new { categoryID = item.ID }, new { @class = "btn btn-primary" })</li>


                    }
                </ul>
            </div>
        </section>



    </div>
    <div class="col-md-9">
        <section class="panel">
            <div class="panel-body">
                <div class="pull-right">
                    <ul class="pagination pagination-sm pro-page-list">
                        @if (TempData["catID"] != null)
                        {
                            <li>@Html.PagedListPager(Model.PagedProducts, page => Url.Action("ShoppingList", new { page, categoryID = TempData["catID"] }))</li>
                        }
                        else
                        {
                            <li>
                                @Html.PagedListPager(Model.PagedProducts, page => Url.Action("ShoppingList", new { page }))
                            </li>

                        }
                    </ul>
                </div>
                
            </div>


        </section>

        <div class="row product-list">


            @foreach (Product item in Model.PagedProducts)
            {
                <div class="col-md-4">
                    <section class="panel">
                        <div class="pro-img-box">

                            @if (item.ImagePath == null)
                            {
                                <img src="~/Pictures/CityLife.jpg" width="100" height="300" alt="Resim Yok" title="@item.ProductName" />

                            }
                            else
                            {
                                <img src="@item.ImagePath" alt="Resim Yok" width="100" height="300" title="@item.ProductName" />
                            }

                            @*Url.Action'in bize verdigi fayda, belli durumlarda ActionLink kullanmak tasarımımıza uygun olmadıgı zamanlarda ortaya cıkar....*@

                            @*@Html.ActionLink("Sepete At","AddToCart",new { id=item.ID},new { @class="adtocart"})*@

                            <a href="@Url.Action("AddToCart",new { id=item.ID})" class="adtocart">
                                <i class="icon-shopping-cart"></i>
                            </a>
                        </div>

                        <div class="panel-body text-center">
                            <h4>
                                <a href="#" class="pro-title">
                                    @item.ProductName.Substring(0, 6)

                                   

                                </a>
                            </h4>
                            <p class="price">$@item.UnitPrice</p>
                        </div>
                    </section>
                </div>
            }





        </div>
    </div>
</div>


@section Sepet{

       <li> <a href="@Url.Action("CartPage","Shopping")">  <i class="icon-shopping-cart"></i> Cart   </a>  </li>

    }

Project.WEBUI/Views/Shopping/SiparisiOnayla.cshtml
@model OrderVM
@{
    ViewBag.Title = "SiparisiOnayla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SiparisiOnayla</h2>

<div class="form">
    @using (Html.BeginForm("SiparisiOnayla", "Shopping", FormMethod.Post, new { @class = "form-horizontal tasi-form" }))
    {
        <div class="form-group">
            <label class="col-sm-2 control-label">Gonderim Adresi </label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.Order.ShippedAddress, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"> Kart Numarası</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentVM.CardNumber, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Kart güvenlik numarası </label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentVM.SecurityNumber, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Kullanım Tarihi Son Yıl</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentVM.CardExpiryYear, new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            <label class="col-sm-2 control-label">Kullanım Tarihi Son Ay </label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentVM.CardExpiryMonth, new { @class = "form-control" })
            </div>
        </div>





        <div class="form-group">
            <label class="col-sm-2 control-label">Kart üzerindeki isim</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.PaymentVM.CardUserName, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">Emailiniz</label>
            <div class="col-sm-10">
                @Html.TextAreaFor(x => x.Order.Email, new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            <label class="col-sm-2 control-label">Onayla</label>
            <div class="col-sm-10">
                <button class="btn btn-primary">Onay</button>
            </div>
        </div>


    }
</div>