Project.WEBUI/Controllers/HomeController.cs
using Project.BLL.DesignPatterns.GenericRepository.ConcRep;
using Project.COMMON.Tools;
using Project.ENTITIES.Models;
using Project.WEBUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.WEBUI.Controllers
{
    public class HomeController : Controller
    {
        AppUserRepository apRep;
        public HomeController()
        {
            apRep = new AppUserRepository();
        }
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login([Bind(Prefix = "AppUser")] AppUser item)
        {
            AppUser yakalanan = apRep.FirstOrDefault(x => x.UserName == item.UserName);
            string decrypted = DantexCrypt.DeCrypt(yakalanan.Password);

            if (item.Password == decrypted && yakalanan != null && yakalanan.Role == ENTITIES.Enums.UserRole.Admin)
            {
                if (!yakalanan.Active)
                {
                    return AktifKontrol();
                }
                Session["admin"] = yakalanan;
                return RedirectToAction("CategoryList", "Category", new { Area = "Admin" });
            }
            else if (yakalanan.Role == ENTITIES.Enums.UserRole.Member)
            {
                if (!yakalanan.Active)
                {
                   return  AktifKontrol();
                }
                Session["member"] = yakalanan;
                return RedirectToAction("ShoppingList", "Shopping");
            }

            ViewBag.KullaniciYok = "Kullanıcı bulunamadı";
            return View();


        }

     
        private ActionResult AktifKontrol()
        {
            ViewBag.AktifDegil = "Lutfen hesabınızı aktif hale getiriniz...Mailinizi kontrol ediniz";
            return View("Login");
        }

    }
}

Project.WEBUI/Controllers/RegisterController.cs
using Project.BLL.DesignPatterns.GenericRepository.ConcRep;
using Project.COMMON.Tools;
using Project.ENTITIES.Models;
using Project.WEBUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.WEBUI.Controllers
{
    public class RegisterController : Controller
    {
        AppUserRepository apRep;
        ProfileRepository apdRep;
        public RegisterController()
        {
            apRep = new AppUserRepository();
            apdRep = new ProfileRepository();
        }
        // GET: Register
        public ActionResult RegisterNow()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegisterNow(AppUserVM apvm)
        {
            AppUser appUser = apvm.AppUser;
            UserProfile profile = apvm.Profile;

            appUser.Password = DantexCrypt.Crypt(appUser.Password); //sifreyi kriptoladık

            //AppUser.Password = DantexCrypt.DeCrypt(apvm.AppUser.Password);

            if (apRep.Any(x=>x.UserName==appUser.UserName))
            {
                ViewBag.ZatenVar = "Kullanıcı ismi daha önce alınmıs";
                return View();
            }
            else if (apRep.Any(x => x.Email == appUser.Email))
            {
                ViewBag.ZatenVar = "Email zaten kayıtlı";
                return View();
            }

            //Kullanıcı basarılı bir şekilde register işlemini tamamladıysa ona mail gönder

            string gonderilecekMail = "Tebrikler...Hesabınız olusturulmustur. Hesabınızı aktive etmek icin https://localhost:44362/Register/Activation/"+appUser.ActivationCode+" linkine tıklayabilirsiniz.";

            MailSender.Send(appUser.Email, body: gonderilecekMail, subject: "Hesap aktivasyon!");
            apRep.Add(appUser); //öncelikle bunu eklemelisiniz. Cnkü AppUser'in ID'si ilk basta olusmalı... Cünkü biz birebir ilişkide AppUser zorunlu alan Profile ise opsiyonel alandır. Dolayısıyla ilk basta AppUser'in ID'si SaveChanges ile olusmalı ki sonra Profile'i rahatca ekleyebilelim...

            if (!string.IsNullOrEmpty(profile.FirstName) || !string.IsNullOrEmpty(profile.LastName) || !string.IsNullOrEmpty(profile.Address))
            {
                profile.ID = appUser.ID;
                apdRep.Add(profile);
            }

            return View("RegisterOk");



        }

        public ActionResult Activation(Guid id)
        {
            AppUser aktifEdilecek = apRep.FirstOrDefault(x => x.ActivationCode == id);
            if (aktifEdilecek != null)
            {
                aktifEdilecek.Active = true;
                apRep.Update(aktifEdilecek);

                TempData["HesapAktifmi"] = "Hesabınız aktif hale getirildi";
                return RedirectToAction("Login","Home");
            }
            TempData["HesapAktifmi"] = "Aktif edilecek hesap bulunamadı";
            return RedirectToAction("Login","Home");
        }

        public ActionResult RegisterOk()
        {
            return View();
        }
    }
}

Project.WEBUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Hosgeldiniz</h2>

Project.WEBUI/Views/Home/Login.cshtml
@model AppUserVM
<!DOCTYPE html>

@{
    Layout = null;
}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>FlatLab - Flat & Responsive Bootstrap Admin Template</title>

    <!-- Bootstrap core CSS -->
    <link href="~/OuterTools/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/OuterTools/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="~/OuterTools/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/OuterTools/css/style.css" rel="stylesheet">
    <link href="~/OuterTools/css/style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
</head>

<body class="login-body">

    <div class="container">
        @TempData["HesapAktifmi"]
        @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { @class = "form-signin" }))
        {
            if (ViewBag.AktifDegil != null)
            {
                <h2>@ViewBag.AktifDegil</h2>
            }

            <h2 class="form-signin-heading"> Uye olunuz  </h2>
            <div class="login-wrap">

                @Html.TextBoxFor(x => x.AppUser.UserName, new { @class = "form-control", placeholder = "Kullanıcı ismi giriniz" })

                @Html.PasswordFor(x => x.AppUser.Password, new { @class = "form-control", placeholder = "Sifre Giriniz" })



                <br />
                <button class="btn btn-lg btn-login btn-block" type="submit">Log In</button>

                <div class="registration">

                    @Html.ActionLink("Üye ol", "RegisterNow", "Register")

                </div>

            </div>
        }

    </div>



    <!-- js placed at the end of the document so the pages load faster -->
    <script src="~/OuterTools/js/jquery.js"></script>
    <script src="~/OuterTools/js/bootstrap.min.js"></script>


</body>
</html>